---
- name: create hadoop data home
  file:
    path: "{{ hadoop_data }}"
    state: directory
    mode: '0755'
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  become: yes

- name: create hadoop config file
  template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
  with_items: "{{ hadoop_conf_files }}"
  remote_user: "{{ hadoop_user }}"

- name: link hadoop config file
  file:
    src: "{{ item.dest }}"
    dest: "{{ hadoop_home }}/etc/hadoop/{{ item.name }}"
    state: link
    force: yes
  with_items: "{{ hadoop_conf_files }}"
  remote_user: "{{ hadoop_user }}"

- name: make directory for log
  file:
    path: "{{ hadoop_home }}/logs"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: '0777'
    state: 'directory'
  remote_user: "{{ hadoop_user }}"

- name: make directory for log
  file:
    src: "{{ hadoop_home }}/logs"
    dest: /var/log/hadoop
    owner: "{{ hadoop_user }}"
    mode: '0777'
    state: 'link'
  become: yes

- name: env HADOOP_HOME for "{{ hadoop_user }}"
  lineinfile:
    path: "/home/{{ hadoop_user }}/.profile"
    line: export HADOOP_HOME="\"{{ hadoop_home }}\""
    state: present
  remote_user: "{{ hadoop_user }}"

- name: env PATH for "{{ hadoop_user }}"
  lineinfile:
    path: "/home/{{ hadoop_user }}/.profile"
    line: export PATH="\"{{ hadoop_home }}/bin\":$PATH"
    state: present
  remote_user: "{{ hadoop_user }}"
