---
- name: create directory for upload package and config
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "{{ packages_directory }}"
    - "{{ conf_directory }}"
    - "{{ opt_directory }}"
- name: create hadoop package home
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes
  with_items: "{{ hadoop_homes }}"
  remote_user: "{{ user }}"
- name: create hadoop data home
  file:
    path: "{{ hadoop_data }}"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes
  remote_user: "{{ user }}"
- name: upload hadoop software
  copy:
    src: "files/{{ item }}"
    dest: "/home/{{ user }}/{{ packages_directory }}"
  with_items: "{{ hadoop_packages }}"
  remote_user: "{{ user }}"
- name: extract hadoop software
  unarchive:
    src: "$HOME/{{ packages_directory }}/{{ item.package }}"
    dest: "{{ item.dst }}"
    remote_src: yes
    extra_opts: 
      - --strip-components=1
  with_items: "{{ hadoop_unarchives }}"
  remote_user: "{{ user }}"
