roles:
  -
    name: namenode
    count: 1
    hostname_template: nn%02i
    description: namenode
    enabled: false
  -
    name: secondary_namenode
    count: 1
    hostname_template: sn%02i
    description: secondary namenode
    cpus: 2
    memory: 6144
  -
    name: datanodes
    count: 3
    hostname_template: dn%02i
    description: datanode
  -
    name: resourcemanager
    count: 1
    hostname_template: rs%02i
    description: resource manager
  -
    name: proxyserver
    count: 1
    hostname_template: wp%02i
    description: proxy
  -
    name: sparkmaster
    count: 1
    hostname_template: sm%02i
    description: spark master
  -
    name: timelineserver
    count: 1
    hostname_template: ts%02i
    description: timeline server
  -
    name: historyserver
    count: 1
    hostname_template: hs%02i
    description: history server
  -
    name: hive
    count: 2
    hostname_template: hv%02i
    description: hive
  -
    name: metastore
    count: 1
    hostname_template: ms%02i
    description: metastore server
  -
    name: db
    count: 2
    hostname_template: ps%02i
    description: postgresql
  -
    name: lab
    count: 1
    hostname_template: lab%02i
    description: lab
    enabled: true
node:
  box: ubuntu/xenial64
  box_url: ubuntu/xenial64
  cpus: 2
  memory: 4096
  prefix: hadoop
  domain: thuvh.local
  ansible_python_interpreter: /usr/bin/python3
  ansible_ssh_private_key_file: files/id_rsa
net:
  private_nic_type: 82545EM
  network_type: public_network
  bridge:
    - eno1
    - "en4: Ethernet"
    - "en1: Wi-Fi (AirPort)"
ip:
  node: 192.168.10.210
