all:
  children:
    namenode:
      hosts:
        nn01:
          ansible_host: nn01.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
    secondary_namenode:
      hosts:
        sn01:
          ansible_host: sn01.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
    datanodes:
      hosts:
        dn01:
          ansible_host: dn01.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
        dn02:
          ansible_host: dn02.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
        dn03:
          ansible_host: dn03.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
    resourcemanager:
      hosts:
        rs01:
          ansible_host: rs01.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
    proxyserver:
      hosts:
        wp01:
          ansible_host: wp01.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
    sparkmaster:
      hosts:
        sm01:
          ansible_host: sm01.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
    timelineserver:
      hosts:
        ts01:
          ansible_host: ts01.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
    historyserver:
      hosts:
        hs01:
          ansible_host: hs01.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
    db:
      hosts:
        ps01:
          ansible_host: ps01.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
        ps02:
          ansible_host: ps02.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
    lab:
      hosts:
        lab01:
          ansible_host: lab01.thuvh.local
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: files/id_rsa
