---
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
- name: Upgrade all packages to the latest version
  apt:
    upgrade: true
    state: latest
  become: yes
- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes
- name: Install OpenJdk.
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ java_packages }}"
  become: yes
- name: Copy Java Home Script
  template: src=java_home.sh dest=/etc/profile.d
  become: yes
- name: mark java version
  dpkg_selections: name={{ item }} selection=hold
  with_items: "{{ java_packages }}"
  become: yes
