---
- name: stop resourcemanager
  supervisorctl:
    name: resourcemanager
    state: stopped
  become: yes
  when: resourcemanager_config or resourcemanager_stop
  ignore_errors: yes

- name: Template a file to /etc/supervisor/conf.d/hadoop.conf
  template:
    src: hadoop.conf.j2
    dest: /etc/supervisor/conf.d/hadoop.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: resourcemanager_config
  notify:
    - update supervisorctl config file

- name: start resourcemanager
  supervisorctl:
    name: resourcemanager
    state: started
  become: yes
  when: resourcemanager_config or resourcemanager_start
  ignore_errors: yes
