---
- name: stop resourcemanager
  supervisorctl:
    name: resourcemanager
    state: stopped
  become: yes
  ignore_errors: yes

- name: update supervisorctl config of resourcemanager
  supervisorctl:
    name: resourcemanager
    state: absent
  become: yes

- name: Template a file to /etc/supervisor/conf.d/hadoop.conf
  template:
    src: hadoop.conf.j2
    dest: /etc/supervisor/conf.d/hadoop.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: update supervisort config for resourcemanager
  supervisorctl:
    name: resourcemanager
    state: present
  become: yes

- name: start resourcemanager
  supervisorctl:
    name: resourcemanager
    state: started
  become: yes
  ignore_errors: yes
