---
domain: thuvh.local
packages:
 - "ntp"
 - "unzip"
 - "htop"
 - "supervisor"

# java version
jvm_home: "/usr/lib/jvm"
java_packages:
 - "openjdk-8-jdk"

packages_directory: archives
conf_directory: conf
opt_directory: opt

hadoop_user: hdfs
hadoop_group: hdfs
hive_user: hive
hive_group: hive

hadoop_package: hadoop-3.1.2.tar.gz
hive_package: apache-hive-3.1.1-bin.tar.gz
spark_package: spark-2.4.3-bin-hadoop2.7.tgz

hadoop_packages:
  - "{{ hadoop_package }}"
  - "{{ spark_package }}"

hadoop_home: "/home/{{ hadoop_user }}/{{ opt_directory }}/hadoop-3.1.2"
hive_home: "/home/{{ hive_user }}/{{ opt_directory }}/apache-hive-3.1.1-bin"
spark_home: "/home/{{ hadoop_user }}/{{ opt_directory }}/spark-2.4.3-bin-hadoop2.7"

hadoop_homes:
  - "{{ hadoop_home }}"
  - "{{ spark_home }}"

hadoop_unarchives:
  -
    package: "{{ hadoop_package }}"
    dst: "{{ hadoop_home }}"
  -
    package: "{{ spark_package }}"
    dst: "{{ spark_home }}"

hadoop_data: /data/hadoop/

hadoop_conf_files:
  -
    name: core-site.xml
    template: core-site.xml.j2
    dest: "/home/{{ hadoop_user }}/{{ conf_directory }}/core-site.xml"
  -
    name: hdfs-site.xml
    template: hdfs-site.xml.j2
    dest: "/home/{{ hadoop_user }}/{{ conf_directory }}/hdfs-site.xml"
  -
    name: yarn-site.xml
    template: yarn-site.xml.j2
    dest: "/home/{{ hadoop_user }}/{{ conf_directory }}/yarn-site.xml"
  -
    name: mapred-site.xml
    template: mapred-site.xml.j2
    dest: "/home/{{ hadoop_user }}/{{ conf_directory }}/mapred-site.xml"
  -
    name: hadoop-env.sh
    template: hadoop-env.sh.j2
    dest: "/home/{{ hadoop_user }}/{{ conf_directory }}/hadoop-env.sh"

hive_conf_files:
  -
    name: hive-env.sh
    template: hive-env.sh.j2
    dest: "/home/{{ hive_user }}/{{ conf_directory }}/hive-env.sh"
  -
    name: hive-log4j2.properties
    template: hive-log4j2.properties.j2
    dest: "/home/{{ hive_user }}/{{ conf_directory }}/hive-log4j2.properties"
  -
    name: hive-site.xml
    template: hive-site.xml.j2
    dest: "/home/{{ hive_user }}/{{ conf_directory }}/hive-site.xml"
  -
    name: tez-site.xml
    template: tez-site.xml.j2
    dest: "/home/{{ hive_user }}/{{ conf_directory }}/tez-site.xml"

hadoop_conf:
  namenode:
    host: "nn01.{{ domain }}"
    port: 8092
  dfs:
    blocksize: 134217728
  yarn:
    log_aggregation_enable: false
    resourcemanager:
      hostname: "rs01.{{ domain }}"
    scheduler:
      minimum_allocation_mb: 1024
      maximum_allocation_mb: 4096
    nodemanager:
      resource:
        memory_mb: 8192
    web_proxy:
      address: "wp01.{{ domain }}:9046"
    timeline_service:
      enabled: true
      version: "1.5"
      hostname: "ts01.{{ domain }}"
      http_cross_origin:
        enabled: false
      address: "ts01.{{ domain }}:64000"
  mapreduce:
    jobhistory:
      address: "hs01.{{ domain }}"

hive_conf:
  metastore:
    url: jdbc:postgresql://192.168.10.88:5432/hivedb
    drivername: org.postgresql.Driver
    username: hiveuser
    password: h1vEp@&&vv0rd
