---
- name: format namenode (force)
  shell: /bin/bash -lc "{{ hadoop_home }}/bin/hdfs namenode -format -force"
  args:
    chdir: "{{ hadoop_home }}"
    executable: /bin/bash
  remote_user: "{{ hadoop_user }}"
  when: namenode_format

- name: stop namenode
  supervisorctl:
    name: namenode
    state: stopped
  become: yes
  ignore_errors: yes

- name: remove supervisorctl config of namenode
  supervisorctl:
    name: namenode
    state: absent
  become: yes

- name: Template a file to /etc/supervisor/conf.d/hadoop.conf
  template:
    src: hadoop.conf.j2
    dest: /etc/supervisor/conf.d/hadoop.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: update supervisorctl config of namenode
  supervisorctl:
    name: namenode
    state: present
  become: yes

- name: start namenode
  supervisorctl:
    name: namenode
    state: started
  become: yes
  ignore_errors: yes
