---
- hosts: namenode
  vars_files:
   - vars/var_basic.yml
  vars:
    namenode_format: false
    namenode_config: false
    namenode_stop: false
    namenode_start: true
  roles:
    - namenode

- hosts: resourcemanager
  vars_files:
    - vars/var_basic.yml
  vars:
    resourcemanager_config: false
    resourcemanager_start: true
    resourcemanager_stop: false
  roles:
    - resource_manager

- hosts: datanodes
  vars_files:
    - vars/var_basic.yml
  vars:
    node_config: false
    node_start: true
    node_stop: false
  roles:
    - data_manager_node

- hosts: historyserver
  vars_files:
    - vars/var_basic.yml
  vars:
    historyserver_config: false
    historyserver_start: true
    historyserver_stop: false
  roles:
    - history_server

- hosts: proxyserver
  vars_files:
    - vars/var_basic.yml
  vars:
    proxyserver_config: false
    proxyserver_start: true
    proxyserver_stop: false
  roles:
    - proxy_server
