---
- hosts: namenode, resourcemanager, datanodes, historyserver
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
  vars:
    add_user: true
  roles:
    - user
    - profile
    - disk
    - hosts
    - os
    - java
    - hadoop

- hosts: namenode
  vars_files:
   - vars/var_basic.yml
  vars:
    namenode_format: true
  roles:
    - namenode

- hosts: resourcemanager
  vars_files:
    - vars/var_basic.yml
  roles:
    - resource_manager

- hosts: datanodes
  vars_files:
    - vars/var_basic.yml
  roles:
    - data_manager_node

- hosts: historyserver
  vars_files:
    - vars/var_basic.yml
  roles:
    - history_server
