---
# - hosts: namenode, resourcemanager, datanodes, historyserver
#   vars_files:
#    - vars/user.yml
#    - vars/var_basic.yml
#   vars:
#     add_user: true
#   roles:
#     # - user
#     # - profile
#     # - disk
#     # - hosts
#     # - os
#     # - java
#     - hadoop

- hosts: namenode
  vars_files:
   - vars/var_basic.yml
  vars:
    namenode_format: true
    namenode_config: true
    namenode_stop: false
    namenode_start: false
  roles:
    - namenode

- hosts: resourcemanager
  vars_files:
    - vars/var_basic.yml
  vars:
    resourcemanager_config: true
    resourcemanager_start: false
    resourcemanager_stop: false
  roles:
    - resource_manager

- hosts: datanodes
  vars_files:
    - vars/var_basic.yml
  vars:
    node_config: true
    node_start: false
    node_stop: false
  roles:
    - data_manager_node

- hosts: historyserver
  vars_files:
    - vars/var_basic.yml
  vars:
    historyserver_config: true
    historyserver_start: false
    historyserver_stop: false
  roles:
    - history_server

- hosts: proxyserver
  vars_files:
    - vars/var_basic.yml
  vars:
    proxyserver_config: true
    proxyserver_start: false
    proxyserver_stop: false
  roles:
    - proxy_server
