---
- hosts: all:!db
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
  vars:
    add_user: yes
    public_network: yes
  roles:
    - user
    - profile
    - disk
    - hosts
    - os
    - java
    - hadoop
    - reboot
