---
- hosts: proxyserver
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
  vars:
    add_user: true
  roles:
    - user
    - profile
    - disk
    - hosts
    - os
    - java
    - hadoop

- hosts: proxyserver
  vars_files:
   - vars/var_basic.yml
  vars:
    namenode_format: true
  roles:
    - proxy_server
