---
- name: stop historyserver
  supervisorctl:
    name: historyserver
    state: stopped
  become: yes
  when: historyserver_config or historyserver_stop
  ignore_errors: yes

- name: Template a file to /etc/supervisor/conf.d/hadoop.conf
  template:
    src: hadoop.conf.j2
    dest: /etc/supervisor/conf.d/hadoop.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: historyserver_config
  notify:
    - update supervisorctl config file

- name: start historyserver
  supervisorctl:
    name: historyserver
    state: started
  become: yes
  when: historyserver_config or historyserver_start
  ignore_errors: yes
