---
- name: start history server
  shell: "{{ hadoop_home }}/bin/mapred --daemon start historyserver"
  args:
    chdir: "{{ hadoop_home }}"
  remote_user: "{{ hadoop_user }}"
  when: history_server_start
- name: stop history server
  shell: "{{ hadoop_home }}/bin/mapred --daemon stop historyserver"
  args:
    chdir: "{{ hadoop_home }}"
  remote_user: "{{ hadoop_user }}"
  when: history_server_stop
