---
- name: update supervisort config of datanode
  supervisorctl:
    name: datanode
    state: absent
  become: yes

- name: update supervisort config for nodemanager
  supervisorctl:
    name: nodemanager
    state: absent
  become: yes

- name: Template a file to /etc/files.conf
  template:
    src: hadoop.conf.j2
    dest: /etc/supervisor/conf.d/hadoop.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: update supervisort config for datanode
  supervisorctl:
    name: datanode
    state: present
  become: yes

- name: update supervisort config for nodemanager
  supervisorctl:
    name: nodemanager
    state: present
  become: yes
