---
- name: Template a file to /etc/files.conf
  template:
    src: hadoop.conf.j2
    dest: /etc/supervisor/conf.d/hadoop.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: update supervisort config for datanode
  supervisorctl:
    name: datanode
    state: present
  become: yes

- name: update supervisort config for nodemanager
  supervisorctl:
    name: nodemanager
    state: present
  become: yes

- name: start datanode
  supervisorctl:
    name: datanode
    state: start
  become: yes
  when: datanode_start

- name: stop datanode
  supervisorctl:
    name: datanode
    state: stopped
  become: yes
  when: datanode_stop

- name: start nodemanager
  supervisorctl:
    name: nodemanager
    state: start
  become: yes
  when: nodemanager_start

- name: stop nodemanager
  supervisorctl:
    name: nodemanager
    state: stopped
  become: yes
  when: nodemanager_stop
