---
- name: start datanode
  shell: /bin/bash -lc "{{ hadoop_home }}/bin/hdfs --daemon start datanode"
  args:
    chdir: "{{ hadoop_home }}"
    executable: /bin/bash
  remote_user: "{{ hadoop_user }}"
  when: datanode_start

- name: stop datanode
  shell: /bin/bash -lc "{{ hadoop_home }}/bin/hdfs --daemon stop datanode"
  args:
    chdir: "{{ hadoop_home }}"
    executable: /bin/bash
  remote_user: "{{ hadoop_user }}"
  when: datanode_stop

- name: start node manager
  shell: /bin/bash -lc "{{ hadoop_home }}/bin/yarn --daemon start nodemanager"
  args:
    chdir: "{{ hadoop_home }}"
    executable: /bin/bash
  remote_user: "{{ hadoop_user }}"
  when: nodemanager_start

- name: stop node manager
  shell: /bin/bash -lc "{{ hadoop_home }}/bin/yarn --daemon stop nodemanager"
  args:
    chdir: "{{ hadoop_home }}"
    executable: /bin/bash
  remote_user: "{{ hadoop_user }}"
  when: nodemanager_stop
