---
- name: stop datanode
  supervisorctl:
    name: datanode
    state: stopped
  become: yes
  ignore_errors: yes

- name: stop nodemanager
  supervisorctl:
    name: nodemanager
    state: stopped
  become: yes
  ignore_errors: yes

- name: Template a file to /etc/supervisor/conf.d/hadoop.conf
  template:
    src: hadoop.conf.j2
    dest: /etc/supervisor/conf.d/hadoop.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
    - update supervisorctl config file

- name: start datanode
  supervisorctl:
    name: datanode
    state: started
  become: yes
  ignore_errors: yes

- name: start nodemanager
  supervisorctl:
    name: nodemanager
    state: started
  become: yes
  ignore_errors: yes
